### ISSUE TITLE
fix too long videos

### ISSUE THREAD

**Issue by adnjoo** [adnjoo/fast-youtube-summary#25]
e.g. https://www.youtube.com/watch?v=GEf6X-FueMo&pp=ygUPcGV0ZXJzb24gaGFycmlz

**Comment by adnjoo** [comment]
![Screenshot 2024-11-17 at 8 40 43 AM](https://github.com/user-attachments/assets/2bf06faf-38e9-463a-a34c-c94427ae7e4a)

**Comment by adnjoo** [comment]
```bash
Error processing summary: Error: 400 This model's maximum context length is 16385 tokens. However, your messages resulted in 27538 tokens. Please reduce the length of the messages.
    at async summarizeTranscript (webpack:///app/api/summarize/summarizeTranscript.ts?a904:24:19)
    at async GET (webpack:///app/api/summarize/route.ts?2620:81:27)
    at async AppRouteRouteModule.do (file:///Users/andrewnjoo/Desktop/summatube/web/node_modules/next/dist/compiled/next-server/dist/src/server/route-modules/app-route/module.ts:525:14)
    at async AppRouteRouteModule.handle (file:///Users/andrewnjoo/Desktop/summatube/web/node_modules/next/dist/compiled/next-server/dist/src/server/route-modules/app-route/module.ts:652:30)
    at async doRender (file:///Users/andrewnjoo/Desktop/summatube/web/node_modules/next/src/server/base-server.ts:2570:29)
    at async responseGenerator (file:///Users/andrewnjoo/Desktop/summatube/web/node_modules/next/src/server/base-server.ts:3066:21)
    at async DevServer.renderToResponseWithComponentsImpl (file:///Users/andrewnjoo/Desktop/summatube/web/node_modules/next/src/server/base-server.ts:3121:23)
    at async DevServer.renderPageComponent (file:///Users/andrewnjoo/Desktop/summatube/web/node_modules/next/src/server/base-server.ts:3676:15)
    at async DevServer.renderToResponseImpl (file:///Users/andrewnjoo/Desktop/summatube/web/node_modules/next/src/server/base-server.ts:3738:23)
    at async DevServer.pipeImpl (file:///Users/andrewnjoo/Desktop/summatube/web/node_modules/next/src/server/base-server.ts:1738:20)
    at async NextNodeServer.handleCatchallRenderRequest (file:///Users/andrewnjoo/Desktop/summatube/web/node_modules/next/src/server/next-server.ts:1032:6)
    at async DevServer.handleRequestImpl (file:///Users/andrewnjoo/Desktop/summatube/web/node_modules/next/src/server/base-server.ts:1498:8)
    at async (file:///Users/andrewnjoo/Desktop/summatube/web/node_modules/next/src/server/dev/next-dev-server.ts:514:13)
    at async Span.traceAsyncFn (file:///Users/andrewnjoo/Desktop/summatube/web/node_modules/next/src/trace/trace.ts:143:13)
    at async DevServer.handleRequest (file:///Users/andrewnjoo/Desktop/summatube/web/node_modules/next/src/server/dev/next-dev-server.ts:512:19)
    at async invokeRender (file:///Users/andrewnjoo/Desktop/summatube/web/node_modules/next/src/server/lib/router-server.ts:284:10)
    at async handleRequest (file:///Users/andrewnjoo/Desktop/summatube/web/node_modules/next/src/server/lib/router-server.ts:530:15)
    at async requestHandlerImpl (file:///Users/andrewnjoo/Desktop/summatube/web/node_modules/next/src/server/lib/router-server.ts:576:6)
    at async Server.requestListener (file:///Users/andrewnjoo/Desktop/summatube/web/node_modules/next/src/server/lib/start-server.ts:146:6)
  22 |     `;
  23 |
> 24 |   const response = await OPEN_AI.chat.completions.create({
     |                   ^
  25 |     model: OpenAIModels.GPT_3_5_TURBO,
  26 |     messages: [
  27 |       { {
  status: 400,
  headers: [Object],
  request_id: 'req_d0e43674d58868c44c6f3c1db13bf50f',
  error: [Object],
  code: 'context_length_exceeded',
  param: 'messages',
  type: 'invalid_request_error'
}
 GET /api/summarize?video_id=I8Xc2_FtpHI&save=true 500 in 4700ms

```
